// mode13.c - A demo of all the mode 13h functions for this chapter

#include <io.h>
#include <conio.h>
#include <stdio.h>
#include <stdlib.h>
#include <dos.h>
#include <bios.h>
#include <fcntl.h>
#include <memory.h>
#include <malloc.h>
#include <math.h>
#include <string.h>

#include "black3.h"  // the header file for this module

// VBE_DEMO_M16/VBE_DEMO_L32 select a higher-colour-depth variant of the
// same VBE_SUPPORT build (define alongside VBE_SUPPORT, not instead of it).
#if defined(VBE_DEMO_L32)
    #define DEMO_WIDTH  1024
    #define DEMO_HEIGHT 768
#elif defined(VBE_DEMO_M16)
    #define DEMO_WIDTH  800
    #define DEMO_HEIGHT 600
#elif defined(VBE_SUPPORT)
    #define DEMO_WIDTH  640
    #define DEMO_HEIGHT 480
#endif

#ifdef VBE_DEMO_M16
// Pack R, G, B (each 0..255) into a 16bpp R5G6B5 colour value.
// R: 5 bits -> bits 15-11   G: 6 bits -> bits 10-5   B: 5 bits -> bits 4-0
#define RGB16(r,g,b) \
    ((unsigned short)((((unsigned)(r) & 0xF8u) << 8) | \
                      (((unsigned)(g) & 0xFCu) << 3) | \
                       ((unsigned)(b) >> 3)))
// Random high colour: independent R, G, B bytes from rand().
#define RAND_COLOR16() \
    RGB16((rand()&0xFF),(rand()&0xFF),(rand()&0xFF))
#endif

#ifdef VBE_DEMO_L32
// Random true colour: independent R, G, B bytes from rand().
#define RAND_COLOR32() \
    RGB32((rand()&0xFF),(rand()&0xFF),(rand()&0xFF))
#endif

// literal 15 is a palette index (white, once the demo's default palette is
// in effect) - meaningless at 16/32bpp, where it packs to a near-black,
// faintly blue pixel instead. Use real white there.
#if defined(VBE_DEMO_L32)
#define TEXT_COLOR ((int)RGB32(255, 255, 255))
#elif defined(VBE_DEMO_M16)
#define TEXT_COLOR ((int)RGB16(255, 255, 255))
#else
#define TEXT_COLOR 15
#endif

void main(int argc, char** argv) {
#if !defined(VBE_DEMO_M16) && !defined(VBE_DEMO_L32)
    RgbColor color;
    RgbPalette savePalette;
#endif
    int index;

    srand(time(NULL));

#ifdef VBE_SUPPORT
#if defined(VBE_DEMO_L32)
    printf("\nHit any key to switch to SVGA mode (1024x768x32)\n");
#elif defined(VBE_DEMO_M16)
    printf("\nHit any key to switch to SVGA mode (800x600x16)\n");
#else
    printf("\nHit any key to switch to SVGA mode (640x480x256)\n");
#endif
    getch();

    // set the graphics mode to SVGA
#if defined(VBE_DEMO_L32)
    if (!setGraphicsModeVesa(DEMO_WIDTH, DEMO_HEIGHT, 32)) {
        printf("Error: 1024x768x32 mode not available.\n");
        printf("Your card may not support this resolution at 32bpp,\n");
        printf("or may not have enough VRAM (requires 3 MB).\n");
        return;
    }
#elif defined(VBE_DEMO_M16)
    if (!setGraphicsModeVesa(DEMO_WIDTH, DEMO_HEIGHT, 16)) {
        printf("Error: 800x600x16 mode not available.\n");
        printf("Your card may not support this resolution at 16bpp.\n");
        return;
    }
#else
    setGraphicsModeVesa(DEMO_WIDTH, DEMO_HEIGHT, 8);
#endif
#else
    printf("\nHit any key to switch to mode 13h\n");
    getch();

    // set the graphics mode to mode 13h
    setGraphicsMode(GRAPHICS_MODE13);
#endif

#ifdef DOS_32_BIT
    // RomCharSet starts NULL under DOS_32_BIT (16-bit builds read the BIOS
    // ROM font directly) - load whichever font size matches this resolution
    // (font16.bin/font24.bin/font32.bin are generated by exp_font.exe
    // alongside the base font.bin)
#if defined(VBE_DEMO_L32)
    loadFontSet("font32.bin", 32);
#elif defined(VBE_DEMO_M16)
    loadFontSet("font24.bin", 24);
#elif defined(VBE_SUPPORT)
    loadFontSet("font16.bin", 16);
#else
    initRomCharSet();
#endif
#endif

    // show some text
    printString(0, 0, TEXT_COLOR, "Hit a key to see text printing          ", 0);
    getch();

    // print a few hundred strings on the screen - printChar clips at the
    // screen edges, so this can use the same full-width/height random
    // range as the pixel-plot/line loops below instead of bunching every
    // string into a narrow strip near x=0 to guarantee it fits unclipped
#ifdef VBE_SUPPORT
    for (index = 0; index < 1000; index++) {
        printString(
            rand() % DEMO_WIDTH,
            rand() % DEMO_HEIGHT,
#if defined(VBE_DEMO_L32)
            (int)RAND_COLOR32(),
#elif defined(VBE_DEMO_M16)
            (int)RAND_COLOR16(),
#else
            rand() % 256,
#endif
            "This is a demo of text printing",
            1);
    }
#else
    for (index = 0; index < 1000; index++) {
        printString(
            rand() % (320 - 256),
            rand() % 190,
            rand() % 256,
            "This is a demo of text printing",
            1);
    }
#endif

    printString(0, 0, TEXT_COLOR, "Hit a key to see screen filling         ", 0);
    getch();

    // fill the screen dark grey
#if defined(VBE_DEMO_L32)
    fillScreen((int)RGB32(32, 32, 32));
#elif defined(VBE_DEMO_M16)
    fillScreen((int)RGB16(32, 32, 32));
#else
    fillScreen(8);
#endif
    printString(0, 0, TEXT_COLOR, "Hit a key to see pixel plotting         ", 0);
    getch();

    // plot 10000 random pixels
    for (index = 0; index < 10000; index++) {
#if defined(VBE_DEMO_L32)
        writePixel(rand() % DEMO_WIDTH, rand() % DEMO_HEIGHT, (int)RAND_COLOR32());
#elif defined(VBE_DEMO_M16)
        writePixel(rand() % DEMO_WIDTH, rand() % DEMO_HEIGHT, (int)RAND_COLOR16());
#elif defined(VBE_SUPPORT)
        writePixel(rand() % DEMO_WIDTH, rand() % DEMO_HEIGHT, 12);
#else
        writePixel(rand() % 320, rand() % 200, 12);
#endif
    }

    printString(0, 0, TEXT_COLOR, "Hit a key to see lines                  ", 0);
    getch();

    // draw 1000 randomly positioned horizontal and vertical lines
    for (index = 0; index < 1000; index++) {
#if defined(VBE_DEMO_L32)
        lineH(rand() % DEMO_WIDTH, rand() % DEMO_WIDTH, rand() % DEMO_HEIGHT, (int)RAND_COLOR32());
        lineV(rand() % DEMO_HEIGHT, rand() % DEMO_HEIGHT, rand() % DEMO_WIDTH, (int)RAND_COLOR32());
#elif defined(VBE_DEMO_M16)
        lineH(rand() % DEMO_WIDTH, rand() % DEMO_WIDTH, rand() % DEMO_HEIGHT, (int)RAND_COLOR16());
        lineV(rand() % DEMO_HEIGHT, rand() % DEMO_HEIGHT, rand() % DEMO_WIDTH, (int)RAND_COLOR16());
#elif defined(VBE_SUPPORT)
        lineH(rand() % DEMO_WIDTH, rand() % DEMO_WIDTH, rand() % DEMO_HEIGHT, rand() % 256);
        lineV(rand() % DEMO_HEIGHT, rand() % DEMO_HEIGHT, rand() % DEMO_WIDTH, rand() % 256);
#else
        lineH(rand() % 320, rand() % 320, rand() % 200, rand() % 256);
        lineV(rand() % 200, rand() % 200, rand() % 320, rand() % 256);
#endif
    }

    // color registers (the VGA DAC) only affect what's displayed in 8bpp
    // indexed-color modes - at 16/32bpp every pixel already carries its own
    // RGB value directly, so rewriting the DAC has no visible effect at
    // all. Skip the whole demo rather than making the user sit through a
    // ~14 second no-op loop (256 iterations x timeDelay(1)).
#if !defined(VBE_DEMO_M16) && !defined(VBE_DEMO_L32)
    printString(0, 0, TEXT_COLOR, "Hit a key to change color registers     ", 0);
    getch();

    // save the palette
    readPalette(0, 255, &savePalette);

    // change the palette
    for (index = 0; index < 256; index++) {
        // set the color to bright green
        color.red   = 0;
        color.green = 63;
        color.blue  = 0;

        // change the currently index color register
        writeColorReg(index, &color);

        // let user see it happen
        timeDelay(1);
    }

    // make color 15 visible so user can read text
    color.red   = 63;
    color.green = 63;
    color.blue  = 63;
    writeColorReg(15, &color);

    printString(0, 0, TEXT_COLOR, "Hit a key to restore palette            ", 0);
    getch();

    // restore palette
    writePalette(&savePalette);
#endif

    printString(0, 0, TEXT_COLOR, "Hit a key to switch back to text mode   ", 0);
    getch();

    // restore graphics mode to text
    setGraphicsMode(TEXT_MODE);
}
