// floater.c - A demo of 2D terrain following

#include <io.h>
#include <conio.h>
#include <stdio.h>
#include <stdlib.h>
#include <dos.h>
#include <bios.h>
#include <fcntl.h>
#include <memory.h>
#include <malloc.h>
#include <math.h>
#include <string.h>
#ifdef VBE_SUPPORT
#include <time.h>
#endif

#include "black3.h"
#include "black4.h"

PcxPicture ImagePcx;    // general PCX image used to load background and imagery

Sprite SpeederSprite;   // the floating speeder

void main(int argc, char** argv) {
    int index,
#ifdef VBE_SUPPORT
        terrY = 384,        // these are used to draw random terrain
#else
        terrY = 160,        // these are used to draw random terrain
#endif
        terrDraw = 1,
        rough,              // roughness of terrain, input by user
        x,
        y,
        hoverHeight = 2;    // minimum terrain following height

    // query user about terrain roughness and terrain following height
    printf("Enter the roughness of terrain from 1-10?");
    scanf("%d", &rough);
    printf("Enter the terrain following height from 1-50?");
    scanf("%d", &hoverHeight);

#ifdef VBE_SUPPORT
    // set the graphics mode to SVGA 640x480x256
    setGraphicsModeVesa(640, 480, 8);

    // create the double buffer
    createDoubleBuffer(480);
#else
    // set the graphics mode to mode 13h
    setGraphicsMode(GRAPHICS_MODE13);

    // create the double buffer
    createDoubleBuffer(200);
#endif

#ifdef DOS_32_BIT
    // load font for text (RomCharSet starts NULL under DOS_32_BIT - 16-bit
    // builds read the BIOS ROM font directly)
#ifdef VBE_SUPPORT
    // font16.bin matches this demo's 640x480 resolution (generated by
    // exp_font.exe alongside the base font.bin)
    loadFontSet("font16.bin", 16);
#else
    initRomCharSet();
#endif
#endif

    // load the imagery for the speeder
    pcxInit(&ImagePcx);
    pcxLoad("floatspd.pcx", &ImagePcx, 1);

    // initialize the speeder
#ifdef VBE_SUPPORT
    spriteInit(&SpeederSprite, 640, 240, 80, 20, 0, 0, 0, 0, 0, 0);
#else
    spriteInit(&SpeederSprite, 320, 100, 40, 10, 0, 0, 0, 0, 0, 0);
#endif

    // extract the bitmaps for the speeder, there are 4 animation cells
    for (index = 0; index < 4; index++) {
        pcxGetSprite(&ImagePcx, &SpeederSprite, index, index, 0);
    }

    // done with this PCX file so delete memory associated with it
    pcxDelete(&ImagePcx);

    // draw the terrain one vertical strip at a time
    // seed the random number generator with current time
#ifdef VBE_SUPPORT
    srand((unsigned)time(NULL));
#else
    srand(*(int FAR*)0x0000046CL);
#endif

#ifdef VBE_SUPPORT
    for (x = 0; x < 640; x++) {
        // test if it's time to change directions
        if (--terrDraw <= 0) {
            terrDraw = rand() % (20 / rough);
            terrY = terrY - 2 + rand() % 5;
        }

        // draw a vertical strip at current x location
        writePixelDb(x, terrY, 15);

        for (y = terrY + 1; y < 480; y++) {
            writePixelDb(x, y, 200 + rand() % 16);
        }
    }
#else
    for (x = 0; x < 320; x++) {
        // test if it's time to change directions
        if (--terrDraw <= 0) {
            terrDraw = rand() % (20 / rough);
            terrY = terrY - 1 + rand() % 3;
        }

        // draw a vertical strip at current x location
        writePixelDb(x, terrY, 15);

        for (y = terrY + 1; y < 200; y++) {
            writePixelDb(x, y, 200 + rand() % 16);
        }
    }
#endif

    // scan background before entering event loop
    spriteUnderClip(&SpeederSprite, DoubleBuffer);

    // put up exit instructions
#ifdef VBE_SUPPORT
    printStringDb(160, 4, 9, "Hit any key to exit", 1);
#else
    printStringDb(80, 2, 9, "Hit any key to exit", 1);
#endif

    // main event loop, process until keyboard hit
    while (!kbhit()) {
        // do animation cycle, erase, move, draw...

        // erase all objects by replacing what was under them
        spriteEraseClip(&SpeederSprite, DoubleBuffer);

        // move speeder

        // if there is no terrain under speeder then apply downward thrust
        // at constant velocity
#ifdef VBE_SUPPORT
        if (!readPixelDb(SpeederSprite.x + 8, SpeederSprite.y + 20 + hoverHeight * 2)) {
            SpeederSprite.y += 4;
        }

        // now horizontal thrust
        SpeederSprite.x -= 12;

        // now probe under speeder for terrain and apply upward thrust
        // if crust is found
        if (readPixelDb(SpeederSprite.x + 8, SpeederSprite.y + 20 + hoverHeight * 2)) {
            SpeederSprite.y -= 4;
        }

        // test if speeder has moved off screen
        if (SpeederSprite.x < -80) {
            SpeederSprite.x = 640;
        }

        // this should never happen, but just in case
        if (SpeederSprite.y > 480) {
            SpeederSprite.y = 480;
        }
#else
        if (!readPixelDb(SpeederSprite.x + 4, SpeederSprite.y + 12 + hoverHeight)) {
            SpeederSprite.y += 2;
        }

        // now horizontal thrust
        SpeederSprite.x -= 6;

        // now probe under speeder for terrain and apply upward thrust
        // if crust is found
        if (readPixelDb(SpeederSprite.x + 4, SpeederSprite.y + 12 + hoverHeight)) {
            SpeederSprite.y -= 2;
        }

        // test if speeder has moved off screen
        if (SpeederSprite.x < -40) {
            SpeederSprite.x = 320;
        }

        // this should never happen, but just in case
        if (SpeederSprite.y > 200) {
            SpeederSprite.y = 200;
        }
#endif

        // animate speeder
        if (++SpeederSprite.currFrame == 4) {
            SpeederSprite.currFrame = 0;
        }

        // ready to draw speeder, but first scan background under it
        spriteUnderClip(&SpeederSprite, DoubleBuffer);
        spriteDrawClip(&SpeederSprite, DoubleBuffer, 1);

        // display double buffer
        displayDoubleBuffer(DoubleBuffer, 0);

        // lock onto 18 frames per second max
        timeDelay(1);
    }

    // exit in a very cool way
    screenTransition(SCREEN_DARKNESS);

    // free up all resources
    spriteDelete(&SpeederSprite);
    deleteDoubleBuffer();
#if defined(DOS_32_BIT) && defined(VBE_SUPPORT)
    freeFontSet();
#elif defined(DOS_32_BIT)
    freeRomCharSet();
#endif
    setGraphicsMode(TEXT_MODE);
}
