// jumper.c - A demo of spider jumping around using patterns

#include <io.h>
#include <conio.h>
#include <stdio.h>
#include <stdlib.h>
#include <dos.h>
#include <bios.h>
#include <fcntl.h>
#include <memory.h>
#include <malloc.h>
#include <math.h>
#include <string.h>

#include "black3.h"
#include "black4.h"

#define NUM_PATTERNS 6

PcxPicture ImagePcx;    // general PCX image used to load background and imagery

Sprite SpiderSprite;    // the jumping spider

// these are the patterns encoded as strings, with a max of 64 commands
// kinda like DNA patterns
char* Patterns[NUM_PATTERNS] = {
    "rrrrrrrrrrrrruuuuuuuuuuuulllllllllllllllldddddddddddddlllllllll.",
    "urururururururururrrrrrrrdrdrdrdrdrdrdrdrlllllllllllllddddllddd.",
    "rrrrurrrrurrrruururururururuulululululululdldldldldrdrdrdrdrdrd.",
    "xxxxxxxxxxxuuuuuuuuuudddduuuudddduuuddduuuddduuuddduuuddduuulll.",
    "rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrruuuuuuuuuuuuuuuuuuuuuuuuuuuuuu.",
    "lllllllllllllllrrrrrrrrrrrrrrrrrddddddddddddddddxxxxxxxrrrrrruu."
};

void main(int argc, char** argv) {
    int index;
    char buffer[64];    // used to print strings

#ifdef VBE_SUPPORT
    // set the graphics mode to SVGA 640x480x256
    setGraphicsModeVesa(640, 480, 8);

    // create the double buffer
    createDoubleBuffer(480);
#else
    // set the graphics mode to mode 13h
    setGraphicsMode(GRAPHICS_MODE13);

    // create the double buffer
    createDoubleBuffer(200);
#endif

#ifdef DOS_32_BIT
    // load font for text (RomCharSet starts NULL under DOS_32_BIT - 16-bit
    // builds read the BIOS ROM font directly)
#ifdef VBE_SUPPORT
    // font16.bin matches this demo's 640x480 resolution (generated by
    // exp_font.exe alongside the base font.bin)
    loadFontSet("font16.bin", 16);
#else
    initRomCharSet();
#endif
#endif

    // load the imagery for the spider
    pcxInit(&ImagePcx);
    pcxLoad("jumpspd.pcx", &ImagePcx, 1);

    // initialize the spider
#ifdef VBE_SUPPORT
    spriteInit(&SpiderSprite, 320, 240, 60, 48, 0, 0, 0, 0, 0, 0);
#else
    spriteInit(&SpiderSprite, 160, 100, 30, 24, 0, 0, 0, 0, 0, 0);
#endif
    SpiderSprite.state = 0; // select pattern one
    SpiderSprite.counter1 = 0;

    // extract the bitmaps for the spider, there are 4 animation cells
    for (index = 0; index < 4; index++) {
        pcxGetSprite(&ImagePcx, &SpiderSprite, index, index, 0);
    }

    // done with this PCX file so delete memory associated with it
    pcxDelete(&ImagePcx);

    // now load the background image
    pcxInit(&ImagePcx);
    pcxLoad("jumpbak.pcx", &ImagePcx, 1);

    // copy PCX image to double buffer
    pcxCopyToBuffer(&ImagePcx, DoubleBuffer);
    pcxDelete(&ImagePcx);

    // scan background before entering event loop
    spriteUnderClip(&SpiderSprite, DoubleBuffer);

    // put up exit instructions
#ifdef VBE_SUPPORT
    printStringDb(160, 4, 9, "Hit any key to exit", 1);
#else
    printStringDb(80, 2, 9, "Hit any key to exit", 1);
#endif

    // main event loop, process until keyboard hit
    while (!kbhit()) {
        // do animation cycle, erase, move draw...
        // erase all objects by replacing what was under them
        spriteEraseClip(&SpiderSprite, DoubleBuffer);

        // BEGIN PATTERN MOTION LOGIC ///////////////////////////////////////////

        // move spider, test if there is still data commands in current pattern
        if (Patterns[SpiderSprite.state][SpiderSprite.counter1] != '.') {
            // what is the command
            switch (Patterns[SpiderSprite.state][SpiderSprite.counter1]) {
                case 'r': // right
                {
                    // move spider
#ifdef VBE_SUPPORT
                    SpiderSprite.x += 8;

                    // test if off edge
                    if (SpiderSprite.x > 640) {
                        SpiderSprite.x = -60;
                    }
#else
                    SpiderSprite.x += 4;

                    // test if off edge
                    if (SpiderSprite.x > 320) {
                        SpiderSprite.x = -30;
                    }
#endif
                } break;

                case 'l': // left
                {
                    // move spider
#ifdef VBE_SUPPORT
                    SpiderSprite.x -= 8;

                    // test if off edge
                    if (SpiderSprite.x < -60) {
                        SpiderSprite.x = 640;
                    }
#else
                    SpiderSprite.x -= 4;

                    // test if off edge
                    if (SpiderSprite.x < -30) {
                        SpiderSprite.x = 320;
                    }
#endif
                } break;

                case 'u': // up
                {
                    // move spider
#ifdef VBE_SUPPORT
                    SpiderSprite.y -= 8;

                    // test if off edge
                    if (SpiderSprite.y < -48) {
                        SpiderSprite.y = 480;
                    }
#else
                    SpiderSprite.y -= 4;

                    // test if off edge
                    if (SpiderSprite.y < -24) {
                        SpiderSprite.y = 200;
                    }
#endif
                } break;

                case 'd': // down
                {
                    // move spider
#ifdef VBE_SUPPORT
                    SpiderSprite.y += 8;

                    // test if off edge
                    if (SpiderSprite.y > 480) {
                        SpiderSprite.y = -48;
                    }
#else
                    SpiderSprite.y += 4;

                    // test if off edge
                    if (SpiderSprite.y > 200) {
                        SpiderSprite.y = -24;
                    }
#endif
                } break;

                case 'x': // do nothing
                {
                } break;

                default:
                    break;
            }

            // increment pattern index
            SpiderSprite.counter1++;
        } else {
            // select a new pattern and reset pattern index
            SpiderSprite.state = rand() % NUM_PATTERNS;
            SpiderSprite.counter1 = 0;
        }

        // END PATTERN MOTION LOGIC //////////////////////////////////////////////

        // animate spider
        if (++SpiderSprite.currFrame == 4) {
            SpiderSprite.currFrame = 0;
        }

        // display current pattern and data
        sprintf(
            buffer,
            "Pattern #%d, data=%c",
            SpiderSprite.state,
            Patterns[SpiderSprite.state][SpiderSprite.counter1]);

#ifdef VBE_SUPPORT
        printStringDb(176, 456, 15, buffer, 0);
#else
        printStringDb(88, 190, 15, buffer, 0);
#endif

        // ready to draw spider, but first scan background under it
        spriteUnderClip(&SpiderSprite, DoubleBuffer);
        spriteDrawClip(&SpiderSprite, DoubleBuffer, 1);

        // display double buffer
        displayDoubleBuffer(DoubleBuffer, 0);

        // lock onto 18 frames per second max
        timeDelay(1);
    }

    // exit in a very cool way
    screenTransition(SCREEN_DARKNESS);

    // free up all resources
    spriteDelete(&SpiderSprite);
    deleteDoubleBuffer();
#if defined(DOS_32_BIT) && defined(VBE_SUPPORT)
    freeFontSet();
#elif defined(DOS_32_BIT)
    freeRomCharSet();
#endif
    setGraphicsMode(TEXT_MODE);
}
