#include <io.h>
#include <conio.h>
#include <stdio.h>
#include <stdlib.h>
#include <dos.h>
#include <bios.h>
#include <fcntl.h>
#include <memory.h>
#include <malloc.h>
#include <math.h>
#include <string.h>

#include "black3.h"
#include "black4.h"
#include "black5.h"
#include "black6.h"
#include "black8.h"
#include "black9.h"
#include "black11.h"

void main(void) {
    int done = 0,
#ifdef VBE_SUPPORT
        // fixed demo layout, doubled to (roughly) the same visual size and
        // position on the bigger screen: x by 640/320, y by 480/200
        x = 280, y = 144,
        xOff2 = -100, yOff2 = 144,
        xOff3 = 60, yOff3 = 192,
        labelMargin = 20,
        lineSpacing = 20,
#else
        x = 140, y = 60,
        xOff2 = -50, yOff2 = 60,
        xOff3 = 30, yOff3 = 80,
        labelMargin = 10,
        lineSpacing = 10,
#endif
        intensity1 = 15,
        intensity2 = 50,
        intensity3 = 5;
    char buffer[80];

    // set graphics mode
#ifdef VBE_SUPPORT
    setGraphicsModeVesa(640, 480, 8);
#else
    setGraphicsMode(GRAPHICS_MODE13);
#endif

#ifdef DOS_32_BIT
    // load the character set for text output (RomCharSet starts NULL
    // under DOS_32_BIT - 16-bit builds read the BIOS ROM font directly)
#ifdef VBE_SUPPORT
    // font16.bin matches this demo's 640x480 resolution (generated by
    // exp_font.exe alongside the base font.bin)
    loadFontSet("font16.bin", 16);
#else
    initRomCharSet();
#endif
#endif

    // alter the palette and introduce some greys
    makeGreyPalette();

    // draw gouraud shaded triangle
    drawTriangle2DGouraud(x, y, x + xOff2, y + yOff2, x + xOff3, y + yOff3, VideoBuffer, intensity1, intensity2, intensity3);

    // label vertices
    printString(x, y - labelMargin, 9, "1", 1);
    printString(x + xOff2 - labelMargin, y + yOff2, 9, "2", 1);
    printString(x + xOff3 + labelMargin, y + yOff3, 9, "3", 1);

    // main loop
    while (!done) {
        // test for key
        if (kbhit()) {
            // get the key
            switch (getch()) {
                case 27: { // escape key
                    // exit system
                    done = 1;
                } break;

                case '7': { // increase vertex 1 intensity
                    if (++intensity1 > 63) {
                        intensity1 = 63;
                    }
                } break;

                case '4': { // decrease vertex 1 intensity
                    if (--intensity1 < 0) {
                        intensity1 = 0;
                    }
                } break;

                case '8': { // increase vertex 2 intensity
                    if (++intensity2 > 63) {
                        intensity2 = 63;
                    }
                } break;

                case '5': { // decrease vertex 2 intensity
                    if (--intensity2 < 0) {
                        intensity2 = 0;
                    }
                } break;

                case '9': { // increase vertex 31 intensity
                    if (++intensity3 > 63) {
                        intensity3 = 63;
                    }
                } break;

                case '6': { // decrease vertex 3 intensity
                    if (--intensity3 < 0) {
                        intensity3 = 0;
                    }
                } break;

                default:
                    break;
            }

            // draw gouraud shaded triangle
            drawTriangle2DGouraud(
                x,
                y,
                x + xOff2,
                y + yOff2,
                x + xOff3,
                y + yOff3,
                VideoBuffer,
                intensity1,
                intensity2,
                intensity3);
        }

        // print out vertex intensities
        sprintf(buffer, "Vertex 1 = %d  ", intensity1);
        printString(0, 0, 12, buffer, 0);

        sprintf(buffer, "Vertex 2 = %d  ", intensity2);
        printString(0, lineSpacing, 12, buffer, 0);

        sprintf(buffer, "Vertex 3 = %d  ", intensity3);
        printString(0, lineSpacing * 2, 12, buffer, 0);
    }

#ifdef DOS_32_BIT
#ifdef VBE_SUPPORT
    freeFontSet();
#else
    freeRomCharSet();
#endif
#endif

    // restore text mode
    setGraphicsMode(TEXT_MODE);
}

