# StarBlazer (16-bit, modem) - ANSWER. Run from repo root; then WAIT FOR CONNECTION.
[serial]
serial1=modem listenport:5000
phonebookfile=phonebook.txt
[autoexec]
@echo off
mount c chap09
mount d audio/DRIVERS
d:
soundrv
midpak
c:
blazer s m
