# StarBlazer (32-bit DOS/4GW, VESA 640x480, IPX) - HOST. Run from repo root; then WAIT FOR CONNECTION.
[dosbox]
machine=svga_s3
[ipx]
ipx=true
[autoexec]
@echo off
mount c blazerx
mount d audio/DRIVERS
d:
soundrv
midpak
c:
ipxnet startserver
blazerx s m
