# StarBlazer (32-bit DOS/4GW, IPX) - HOST. Run from repo root; then WAIT FOR CONNECTION.
[ipx]
ipx=true
[autoexec]
@echo off
mount c blzrx32
mount d audio/DRIVERS
d:
soundrv
midpak
c:
ipxnet startserver
blzrx32 s m
