# StarBlazer (16-bit, IPX) - HOST. Run from repo root; then WAIT FOR CONNECTION.
[ipx]
ipx=true
[autoexec]
@echo off
mount c blzrx
mount d audio/DRIVERS
d:
soundrv
midpak
c:
ipxnet startserver
blzrx s m
